### ISSUE TITLE
cycle_app.py steer axis angle does not work with Dash > 1.9.0

### ISSUE THREAD

**Issue by moorepants** [moorepants/BicycleParameters#50]

**Comment by sandertyu** [comment]
Yep, I took a look at the releases and it looks like the culprit is [v1.11.0](https://github.com/plotly/dash/releases/tag/v1.11.0). The following changes have messed up the method that we just implemented for converting to degrees;

`dash.callback_context.triggered now does NOT reflect any initial values, and DOES reflect EVERY value which has been changed either by activity in the app or as a result of a previous callback. That means that the initial call of a callback with no prerequisite callbacks will list nothing as triggering. For backward compatibility, we continue to provide a length-1 list for triggered, but its id and property are blank strings, and bool(triggered) is False.`

Specifically, the conflict is with the code converting to radians before calculations beginning on line [240](https://github.com/sandertyu/BicycleParameters/blob/b9ab583c3a8fe84ed1d6e6b5f20a90a84c6e186d/bicycleparameters/cycle_app.py#L240). When the app is initially loaded now, the dropdown-menu does not show up among the list that is given from `ctx.triggered`, so it unnecessarily runs the if-statement on line 240. The dash callbacks are now recognizing that the bike-dropdown and range-slider values were never actually altered by any other callback upon load, they were only initialized. The datatable values however are changed by another callback (the one that populates the table), so it occurs as the first entry in the `ctx.triggered` list, and the if statement runs.

The app appears fine on initial load because the callback to calculate the plots receives data from the tables now and NOT from the files directly if the bike-dropdown was triggered as expected. I should be able to find a workaround.
